### ISSUE TITLE
Upload doesn't work with a file that has the name of an older one

### ISSUE THREAD

**Issue by Frollamma** [parmigggiana/attack_scripts#6]
Today, during the challenge I tried to upload a file that had the same name of a previous one, I got a "Service unreachable error" (if I remember correctly). I don't know if the cause is the fact that a file with the same name already existed.

**Comment by parmigggiana** [comment]
This is not the case. Testing locally, overwriting an existing file works as expected. More likely it's an issue of redirecting to localhost instead of the machine's ip; I'll try and see if it's something obvious in the frontend, but further testing is required anyway

**Comment by parmigggiana** [comment]
f5610fa should fix the issue
